### ISSUE TITLE
License

### ISSUE THREAD

**Issue by gdgib-roche** [afuersch/css-percentage-circle#2]
Based on http://www.cssscript.com/pure-css-circular-percentage-bar/, it would appear that this code was intended to be licensed under MIT.  We'd like to make use of the code (and contribute a few fixes) but we can't do that without a clear license. Is there any chance you could add a mention of the MIT license to the README or even better add a LICENSE.txt file with [the text of the MIT license](https://opensource.org/licenses/MIT) in it?

**Comment by afuersch** [comment]
Hey @gdgib-bina, I'll added a LICENSE.txt so you can use the library.

**Comment by gdgib-roche** [comment]
Thank you so much @afuersch!  You rock!
