### ISSUE TITLE
decimals

### ISSUE THREAD

**Issue by SilentGlasses** [afuersch/css-percentage-circle#4]
Not an issue but feature request...  Is there a way to allow decimals?  Would it be possible to show 99.5% ?  For example:

```
<div class="col-xs-4 col-sm-2">
    <div class="inner-content text-center">
        <div class="c100 p99.5 center">
            <span>99.5%</span>
            <div class="slice"><div class="bar"></div><div class="fill"></div></div>
        </div>
        <p><em>default</em></p>
    </div>
</div><!-- /.col -->
```

Not sure how the css calls would work tho...

```
.c100.p99 .bar {
  -webkit-transform: rotate(356.4deg);
  -moz-transform: rotate(356.4deg);
  -ms-transform: rotate(356.4deg);
  -o-transform: rotate(356.4deg);
  transform: rotate(356.4deg);
}
```

**Comment by afuersch** [comment]
Do you really need that kind of precision in the drawn circle?
I think it's enough to use the rounded percentage value e.g. 99% for the circle bar and display the precise value (99.5%) as text. I don't think any human eye can see a difference between 99% and 99.5% in the circle bar.
