### ISSUE TITLE
Realtime change percentage

### ISSUE THREAD

**Issue by bm777** [afuersch/css-percentage-circle#7]
This work if it is to show show static value, But i want to show show value in realtime (dynamically).
How can i do?

**Comment by afuersch** [comment]
I'm not sure if I understand your question.
For displaying dynamically, you have to use javascript and set the appropriate CSS class of the circle.

**Comment by bm777** [comment]
<div class="clearfix">

                <div class="c100 p50 big">   <=== at this level, i want to change it in real time
                    <span>50%</span>
                    <div class="slice">
                        <div class="bar"></div>
                        <div class="fill"></div>
                    </div>
                </div>

**Comment by afuersch** [comment]
Depends on how you generate your HTML code or from where you get your data, but when you use Javascript, just remove the old class "p50" and and set the class you need.
If you use any server side view generation, set the desired CSS class.

**Comment by bm777** [comment]
okay. Thks
